// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace AbsenceLibrary.Models;

public partial class Absence
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public DateTime From { get; set; }

    public DateTime To { get; set; }

    public string Reason { get; set; }

    public bool IsExcused { get; set; }

    [JsonIgnore]
    public virtual Student Student { get; set; }
}