// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AbsenceLibrary.Models;

public partial class Student
{
    public int Id { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Schoolclass { get; set; }

    public virtual ICollection<Absence> Absences { get; set; } = new List<Absence>();
}